### ISSUE TITLE
Coerce to known type

### ISSUE THREAD

**Issue by jeffijoe** [jeffijoe/yenv#12]
For example, given:

```yaml
development:
  PORT: 1337
  SEED: true
```

Running `PORT=80 SEED=false node app.js` will make `PORT` and `SEED` strings. We know from the base config that `PORT` is a number and `SEED` is a boolean, so we should coerce to those.
