### ISSUE TITLE
"compose" option to cascade one or more configs.

### ISSUE THREAD

**Issue by jeffijoe** [jeffijoe/yenv#3]
Proposed syntax:

```yaml
# Use case 1: base configs
base:
  PORT: 1338
  SEED_DATABASE: true

# Use case 2: separating config sections, then composing them later.
auth:
  FB_APP_ID: 123

# Any section can compose, and be composed.
development:
  # "compose" takes an array of strings that map to sections
  compose: [base, auth]
  DEV_MODE: true
production:
 compose: [development]
 # Override here..
 PORT: 80
 SEED_DATABASE: false
```
