### ISSUE TITLE
override nested env

### ISSUE THREAD

**Issue by mybigman** [jeffijoe/yenv#33]
I like to use nested settings

```yaml
development:
  connection:
    DB_HOST: 'localhost'
```
Is it possible to override `DB_HOST`... i tried `connection__DB_HOST` but no go, would be nice to be able to do this?
