### ISSUE TITLE
Compose parse env variables

### ISSUE THREAD

**Issue by arvenom** [jeffijoe/yenv#34]
For example this env.yaml 

```
base:
  API_KEY: 12345
  API_ENDPOINT: https://${SERVICE_NAME_API}-dot-${GC_PROJECT}.${GC_BASE_DOMAIN}/

development:
  DEV: true
  SERVICE_NAME_API: dev-service
  GC_PROJECT: dev-project
  GC_BASE_DOMAIN: dev-base-domain
  ~compose: base

production:
  DEV: false
  SERVICE_NAME_API: prod-service
  GC_PROJECT: prod-project
  GC_BASE_DOMAIN: prod-base-domain
  ~compose: base
```

running `yenv print .env-test.yaml development` 
I would expect to get the variables parsed but receiving 

```
"API_ENDPOINT": "https://${SERVICE_NAME_API}-dot-${GC_PROJECT}.${GC_BASE_DOMAIN}/",
```

anyway to make this work? have quite large env files and this would be great to keep it simple.
