### ISSUE TITLE
Array Processing Option

### ISSUE THREAD

**Issue by ddproxy** [jeffijoe/yenv#5]
If I have an array or list of options (like multiple database connections) I'd like to have a 'default' or an option to inject a closure when the list is being constructed to inject default connection information into that list. Furthermore, this may tie into a larger infrastructure idea to have a defined configuration structure that is used to validate the env.yaml and inject defaults into the resulting environment object.

**Comment by jeffijoe** [comment]
Example? Cause I'm not following.

~ Jeff Hansen

**Comment by ddproxy** [comment]
env.yaml
```yaml
databases:
  default:
    host: localhost
  backup:
    host: 192.168.99.100
```

configuration.yaml
```yaml
database:
  template:
    port: 5432
    type: pg
    user: my_user
    schema: my_database
```

Unfolded
```javascript
console.log(env.database.default);
-> {
  host: localhost
  type: pg
  port: 5432
  user: my_user
  schema: my_database
}
console.log(env.database.backup);
-> {
  host: 192.168.99.100
  type: pg
  port: 5432
  user: my_user
  schema: my_database
}
```

**Comment by jeffijoe** [comment]
Thats what compose does though?

~ Jeff Hansen

**Comment by ddproxy** [comment]
For this to work with compose, I'd have to define the default and backup connections in the base compose declaration.

Another example:
```yaml
database:
  default:
    type: pg
    host: localhost
  backup:
    type: mysql
    host: 192.168.99.100
```

configuration.yaml
```yaml
database:
  pg_template:
    port: 5432
    type: pg
    user: my_user
    schema: my_database
  mysql_template:
    port: 3306
    type: mysql
    user: my_user
    schema: my_database
```

```javascript
console.log(env.database.default);
-> {
  host: localhost
  type: pg
  port: 5432
  user: my_user
  schema: my_database
}
console.log(env.database.backup);
-> {
  host: 192.168.99.100
  type: mysql
  port: 3306
  user: my_user
  schema: my_database
}
```

Or inject a closure into the processing of the database entries (or datasource, whatever) to make decisions on what to inject into the object (based on type or other parameters).

```yaml
datasource:
   streets:
     type: shape
     file: ../data/street.shp
   properties:
     type: pgsql
     schema: properties
```

```
foreach datasource as data:
   if (data.type === 'shape') {
      data.srid = data.srid || 4328;
  } else if (data.type === 'pgsql') {
      data.srid = data.srid || 4328;
      data.buffer = data.buffer || '3';
      data.async = data.async || true;
  }
```

Or the { ...default.type.shape, ...data } equivalent. I have a need for this with very large default sets of parameters that are determined by type (shape, pgsql, wkb, wkt, pbf) and need to make decisions based on that, etc...
