### ISSUE TITLE
Empty sections will nuke non-empty sections for imports

### ISSUE THREAD

**Issue by jeffijoe** [jeffijoe/yenv#8]
```yaml
# env.yaml
~import: other.yaml
development:
  # Empty

# other.yaml
development:
  PORT: 80
```

Causes the `development` to be `null`.
